#pragma once

#if defined (DOUBLE_B)

	// 오버라이드 조합키 정의(이름, 조합할 모드키, 조합할 키코드, 작동 키코드)
	#define OVERRIDE_LIST \
	OVERRIDE_X(WINLT,	MOD_MASK_SHIFT, 	U_WINLT, 	U_WINFLT) \
	OVERRIDE_X(WINUP,	MOD_MASK_SHIFT, 	U_WINUP, 	U_WINFUP) \
	OVERRIDE_X(WINDN,	MOD_MASK_SHIFT, 	U_WINDN, 	U_WINFDN) \
	OVERRIDE_X(WINRT,	MOD_MASK_SHIFT, 	U_WINRT, 	U_WINFRT) \
	OVERRIDE_X(MSLT,	MOD_MASK_SHIFT, 	KC_MS_L,	KC_WH_L) \
	OVERRIDE_X(MSUP,	MOD_MASK_SHIFT, 	KC_MS_U, 	KC_WH_U) \
	OVERRIDE_X(MSDN,	MOD_MASK_SHIFT, 	KC_MS_D, 	KC_WH_D) \
	OVERRIDE_X(MSRT,	MOD_MASK_SHIFT, 	KC_MS_R, 	KC_WH_R) \
	OVERRIDE_X(LT,		MOD_MASK_SHIFT, 	KC_DOT,  	KC_LT) \
	OVERRIDE_X(GT,		MOD_MASK_SHIFT, 	KC_COMM, 	KC_GT) \
	OVERRIDE_X(MINO,	MOD_MASK_SHIFT, 	KC_MINS, 	KC_NO) \
	OVERRIDE_X(MINS,	MOD_MASK_SHIFT, 	KC_UNDS, 	KC_MINS) \
	OVERRIDE_X(EQLNO,	MOD_MASK_SHIFT, 	KC_EQL,		KC_NO) \
	OVERRIDE_X(EQL,		MOD_MASK_SHIFT, 	KC_PLUS, 	KC_EQL)

#else

	// 오버라이드 조합키 정의(이름, 조합할 모드키, 조합할 키코드, 작동 키코드)
	#define OVERRIDE_LIST \
	OVERRIDE_X(WINLT,	MOD_MASK_SHIFT, 	U_WINLT, 	U_WINFLT) \
	OVERRIDE_X(WINUP,	MOD_MASK_SHIFT, 	U_WINUP, 	U_WINFUP) \
	OVERRIDE_X(WINDN,	MOD_MASK_SHIFT, 	U_WINDN, 	U_WINFDN) \
	OVERRIDE_X(WINRT,	MOD_MASK_SHIFT, 	U_WINRT, 	U_WINFRT) \
	OVERRIDE_X(MSLT,	MOD_MASK_SHIFT, 	KC_MS_L, 	KC_WH_L) \
	OVERRIDE_X(MSUP,	MOD_MASK_SHIFT, 	KC_MS_U, 	KC_WH_U) \
	OVERRIDE_X(MSDN,	MOD_MASK_SHIFT, 	KC_MS_D, 	KC_WH_D) \
	OVERRIDE_X(MSRT,	MOD_MASK_SHIFT, 	KC_MS_R, 	KC_WH_R)

#endif
